### ISSUE TITLE
 Couldn't load webviewchromium: findLibrary returned null

### ISSUE THREAD

**Issue by ghost** [pwnall/chromeview#40]
Hi There,

reeally cool solution you have created, we are running android 4.1.1 and want to use your solution but we have a small problem, see error log below.

Could you please help us with this?

Thanks!

Regards Sander

11-30 19:27:52.390: E/AndroidRuntime(760): FATAL EXCEPTION: main
11-30 19:27:52.390: E/AndroidRuntime(760): java.lang.RuntimeException: Unable to create application com.gui.launcher.MyApplication: java.lang.RuntimeException: Cannot load WebView
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4154)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.app.ActivityThread.access$1300(ActivityThread.java:130)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.os.Handler.dispatchMessage(Handler.java:99)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.os.Looper.loop(Looper.java:137)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.app.ActivityThread.main(ActivityThread.java:4745)
11-30 19:27:52.390: E/AndroidRuntime(760):  at java.lang.reflect.Method.invokeNative(Native Method)
11-30 19:27:52.390: E/AndroidRuntime(760):  at java.lang.reflect.Method.invoke(Method.java:511)
11-30 19:27:52.390: E/AndroidRuntime(760):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
11-30 19:27:52.390: E/AndroidRuntime(760):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
11-30 19:27:52.390: E/AndroidRuntime(760):  at dalvik.system.NativeStart.main(Native Method)
11-30 19:27:52.390: E/AndroidRuntime(760): Caused by: java.lang.RuntimeException: Cannot load WebView
11-30 19:27:52.390: E/AndroidRuntime(760):  at org.chromium.android_webview.AwBrowserProcess.loadLibrary(AwBrowserProcess.java:32)
11-30 19:27:52.390: E/AndroidRuntime(760):  at us.costan.chrome.impl.ChromeInitializer.initialize(ChromeInitializer.java:48)
11-30 19:27:52.390: E/AndroidRuntime(760):  at us.costan.chrome.ChromeView.initialize(ChromeView.java:848)
11-30 19:27:52.390: E/AndroidRuntime(760):  at com.gui.launcher.MyApplication.onCreate(MyApplication.java:10)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
11-30 19:27:52.390: E/AndroidRuntime(760):  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4151)
11-30 19:27:52.390: E/AndroidRuntime(760):  ... 10 more
11-30 19:27:52.390: E/AndroidRuntime(760): Caused by: org.chromium.content.common.ProcessInitException
11-30 19:27:52.390: E/AndroidRuntime(760):  at org.chromium.content.app.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:111)
11-30 19:27:52.390: E/AndroidRuntime(760):  at org.chromium.content.app.LibraryLoader.loadNow(LibraryLoader.java:79)
11-30 19:27:52.390: E/AndroidRuntime(760):  at org.chromium.android_webview.AwBrowserProcess.loadLibrary(AwBrowserProcess.java:30)
11-30 19:27:52.390: E/AndroidRuntime(760):  ... 15 more
11-30 19:27:52.390: E/AndroidRuntime(760): Caused by: java.lang.UnsatisfiedLinkError: Couldn't load webviewchromium: findLibrary returned null
11-30 19:27:52.390: E/AndroidRuntime(760):  at java.lang.Runtime.loadLibrary(Runtime.java:365)
11-30 19:27:52.390: E/AndroidRuntime(760):  at java.lang.System.loadLibrary(System.java:535)
11-30 19:27:52.390: E/AndroidRuntime(760):  at org.chromium.content.app.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:105)
11-30 19:27:52.390: E/AndroidRuntime(760):  ... 17 more

**Comment by ronnierap** [comment]
As a user contributed post: have you copied the .pak file from the assets directory to your own project assets directory?

**Comment by ghost** [comment]
Yes i did, i am using it on launcher apk in our own Android 4.1.1 ROM

**Comment by ronnierap** [comment]
I join your side:
Yesterday i was compiling this and this morning i changed our application to incorporate this. With the same results

**Comment by jacques404** [comment]
Same error here... Any fix for this?
