### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found: org.chromium.content.app.LibraryLoader.nativeLibraryLoaded:([Ljava/lang/String;)I

### ISSUE THREAD

**Issue by jy1989** [pwnall/chromeview#51]
Hi

I already follow the Setting Up to setup my project

but it has some error when   ChromeView.initialize(this); in my Application:

![qq20140323133327](https://f.cloud.github.com/assets/1291756/2492711/b19c6554-b24c-11e3-8f49-ee6d4488c4a7.png)

03-23 13:26:35.954: E/AndroidRuntime(20041): java.lang.UnsatisfiedLinkError: Native method not found: org.chromium.content.app.LibraryLoader.nativeLibraryLoaded:([Ljava/lang/String;)I
03-23 13:26:35.954: E/AndroidRuntime(20041):    at org.chromium.content.app.LibraryLoader.nativeLibraryLoaded(Native Method)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at org.chromium.content.app.LibraryLoader.initializeAlreadyLocked(LibraryLoader.java:122)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at org.chromium.content.app.LibraryLoader.ensureInitialized(LibraryLoader.java:63)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at org.chromium.android_webview.AwBrowserProcess$1.run(AwBrowserProcess.java:50)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at org.chromium.base.ThreadUtils.runOnUiThreadBlocking(ThreadUtils.java:28)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at org.chromium.android_webview.AwBrowserProcess.start(AwBrowserProcess.java:46)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at us.costan.chrome.impl.ChromeInitializer.initialize(ChromeInitializer.java:49)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at us.costan.chrome.ChromeView.initialize(ChromeView.java:848)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at com.cjy.delaylink.MainApplication.onCreate(MainApplication.java:10)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4408)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.app.ActivityThread.access$1500(ActivityThread.java:145)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1266)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.os.Handler.dispatchMessage(Handler.java:102)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.os.Looper.loop(Looper.java:136)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at android.app.ActivityThread.main(ActivityThread.java:5081)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at java.lang.reflect.Method.invokeNative(Native Method)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at java.lang.reflect.Method.invoke(Method.java:515)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
03-23 13:26:35.954: E/AndroidRuntime(20041):    at dalvik.system.NativeStart.main(Native Method)

so how to solve that?

thank you

**Comment by shockdesign** [comment]
I'm experiencing the same issues when following the guide. Building with API 19 (4.4.2).. tried with API 17 (4.2.2) as well.

@pwnall Is there anything missing from the setup instructions?

**Comment by kashban** [comment]
Same issue here, both on Android 4.x Emulator and Android 4.4. I added the .pak to my project's assets folder, and in the log I see this:

Trying to load lib /data/app-lib/.../libwebviewchromium.so 0x41a870c8

followed by 

Added shared lib /data/app-lib/.../libwebviewchromium.so 0x41a870c8

So it looks like some native code has been loaded, but still cannot be found be ChromeView. 

@pwnall Any news on this?

**Comment by broschb** [comment]
I am seeing the same issue, has anyone found a resolution for this?

**Comment by hoang8f** [comment]
I faced the same problem, is there any solution ?

**Comment by pradeep2929** [comment]
i also faced same problem ,any one who is help me ?

Error is !!!!

java.lang.reflect.InvocationTargetException

at java.lang.reflect.Method.invokeNative(Native Method)

at java.lang.reflect.Method.invoke(Method.java:515)
 android.app.ActivityThread.pauseGC(ActivityThread.java:5525)

 android.app.ActivityThread.performLaunchActivity
 android.app.ActivityThread.handleLaunchActivity

Thanks in Advance!!!

**Comment by broschb** [comment]
I switched to using crosswalk(https://crosswalk-project.org/) this resolved my issues and was much easier to work with vs. building chromium myself.

**Comment by syamavarma** [comment]
Hi,

Did anyone find a solution to this? 

Thanks :)

**Comment by kashban** [comment]
I gave up using chromeview and changed my App to a native framework with a single standard webview. Using ChromeView to fix issues with the standard webkit webview brought too many new hassles to the table.

**Comment by syamavarma** [comment]
With standard webkit webview, the performance is poor when it comes to android versions before 4.4. I need an alternate implementation of webview which uses chromium or something else to make it fast irrespective of android API level.

**Comment by jiangban** [comment]
Did anyone find a solution to this?
