### ISSUE TITLE
Unable to load ChromeView on  device and Emulator as well.

### ISSUE THREAD

**Issue by himanshumistri** [pwnall/chromeview#53]
I have download you library code and add library in my project and when i start app it give me below crash log Does you known how to resolved this issue ? 

Below is my Crash logs:

04-08 15:39:10.342: E/AndroidRuntime(14052): FATAL EXCEPTION: main
04-08 15:39:10.342: E/AndroidRuntime(14052): Process: com.chromium.webviewdemo, PID: 14052
04-08 15:39:10.342: E/AndroidRuntime(14052): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chromium.webviewdemo/com.chromium.webviewdemo.BrowserActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class us.costan.chrome.ChromeView
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.ActivityThread.access$800(ActivityThread.java:135)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.os.Handler.dispatchMessage(Handler.java:102)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.os.Looper.loop(Looper.java:136)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.ActivityThread.main(ActivityThread.java:5017)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at java.lang.reflect.Method.invokeNative(Native Method)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at java.lang.reflect.Method.invoke(Method.java:515)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at dalvik.system.NativeStart.main(Native Method)
04-08 15:39:10.342: E/AndroidRuntime(14052): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class us.costan.chrome.ChromeView
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.view.LayoutInflater.createView(LayoutInflater.java:620)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at com.chromium.webviewdemo.BrowserActivity$PlaceholderFragment.onCreateView(BrowserActivity.java:64)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.Fragment.performCreateView(Fragment.java:1700)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.BackStackRecord.run(BackStackRecord.java:684)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.Activity.performStart(Activity.java:5240)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
04-08 15:39:10.342: E/AndroidRuntime(14052):    ... 11 more
04-08 15:39:10.342: E/AndroidRuntime(14052): Caused by: java.lang.reflect.InvocationTargetException
04-08 15:39:10.342: E/AndroidRuntime(14052):    at java.lang.reflect.Constructor.constructNative(Native Method)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at android.view.LayoutInflater.createView(LayoutInflater.java:594)
04-08 15:39:10.342: E/AndroidRuntime(14052):    ... 23 more
04-08 15:39:10.342: E/AndroidRuntime(14052): Caused by: java.lang.UnsatisfiedLinkError: Native method not found: org.chromium.android_webview.AwContents.nativeInit:(Lorg/chromium/android_webview/AwWebContentsDelegate;Lorg/chromium/android_webview/AwContentsClientBridge;)I
04-08 15:39:10.342: E/AndroidRuntime(14052):    at org.chromium.android_webview.AwContents.nativeInit(Native Method)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at org.chromium.android_webview.AwContents.<init>(AwContents.java:363)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at org.chromium.android_webview.AwContents.<init>(AwContents.java:323)
04-08 15:39:10.342: E/AndroidRuntime(14052):    at us.costan.chrome.ChromeView.<init>(ChromeView.java:91)
04-08 15:39:10.342: E/AndroidRuntime(14052):    ... 26 more

**Comment by kashban** [comment]
I was unaware ChromeView won't work on Kitkat devices, so I restricted it to Android 4.0-4.3. Now It's running but I only get a white screen. Another issue, already reported.

**Comment by Rajinieraj** [comment]
@Himanshu4003  
Hi I am getting the same issue you mentioned above. 
I am developing in 4.2.2. 
Did you find the solution for that issue ? 
Any idea how to overcome it.

**Comment by himanshumistri** [comment]
@Rajinieraj  Since Last two month i have not recheck this project so yet it's resolved for me.
