### ISSUE TITLE
Native method not found - AwContents.nativeInit

### ISSUE THREAD

**Issue by YaakovDavis** [pwnall/chromeview#8]
I managed building an app that refers to the lib, but I get the following in LogCat when launching it:

E/AndroidRuntime(16110): Caused by: java.lang.UnsatisfiedLinkError: **Native method not found: org.chromium.android_webview.AwContents.nativeInit**:(Lorg/chromium/android_webview/AwWebContentsDelegate;Lorg/chromium/android_webview/AwContentsClientBridge;)I
05-24 20:26:20.149: E/AndroidRuntime(16110):    at org.chromium.android_webview.AwContents.nativeInit(Native Method)
05-24 20:26:20.149: E/AndroidRuntime(16110):    at org.chromium.android_webview.AwContents.<init>(AwContents.java:363)
05-24 20:26:20.149: E/AndroidRuntime(16110):    at org.chromium.android_webview.AwContents.<init>(AwContents.java:323)
05-24 20:26:20.149: E/AndroidRuntime(16110):    at us.costan.chrome.ChromeView.<init>(ChromeView.java:91)

How to resolve?

**Comment by defjamuk** [comment]
Hi, I also get this error. Is thee a workaround or an example on how I can create the ChromeView with getting this error?
Thanks

Andy

**Comment by mlasak** [comment]
Hi Jake456,

it seems that ChromeView is not initialised. Try to add to your src folder a file like MainApplication.java with contents below (change to your package). Then add to your AndroidManifest.xml an attribute to application node: android:name="MainApplication"

Hope this helps.

MainApplication.java:

package com.example.cv;

import us.costan.chrome.ChromeView;
import android.app.Application;

public class MainApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        ChromeView.initialize(this);
    }
}

**Comment by hope4555** [comment]
hi
i get this error when try to play video in the html(video tag)
[ERROR:webmediaplayer_android.cc(176)] Not implemented reached in virtual void webkit_media::WebMediaPlayerAndroid::setRate(double)

I guess need to update the code from chrome since fixed not long ago
